[package]
name = "plumb"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = ["perish"]

[features]
depot = [
  "dep:ureq",
]
radius = [
]
vendor = [
  "dep:runseal",
]
skill = [
  "depot",
  "dep:flate2",
  "dep:tar",
]

[dependencies]
base64 = "0.22"
clap = { version = "4", features = ["derive"] }
flate2 = { version = "1", optional = true }
semver = "1"
serde_json = "1"
sha2 = "0.10"
tar = { version = "0.4", optional = true }
ureq = { version = "3", optional = true }
pin-project-lite = "0.2"
plumb-macro = { path = "../macro", version = "=0.37.6", registry = "perish" }
runseal = { version = "=0.18.4", registry = "perish", default-features = false, optional = true }
serde = { version = "1", features = ["derive"] }
toml = "0.9"

[dev-dependencies]
serde_json = "1"
clap = { version = "4", features = ["derive"] }
flate2 = "1"
tar = "0.4"
serde = { version = "1", features = ["derive"] }
tempfile = "3"
toml = "0.9"

[[test]]
name = "skill"
required-features = ["skill"]

[[test]]
name = "vendor"
path = "tests/vendor/mod.rs"
required-features = ["vendor"]

[[test]]
name = "runtime"
path = "tests/runtime/mod.rs"

[[test]]
name = "proof"
path = "tests/proof/mod.rs"
required-features = ["radius"]

[[test]]
name = "survey"
required-features = ["skill"]
