[[document]]
strategy = "agent"
source = [{ path = ".", seal = "079f32795f46c1655e2c7bddbd8444a0c14e955fa762a9474635a7bb3f143999" }]
target-seal = "36216a4004391b92927f30e029a419a90a1d7ef590ba48b708457242fde98c4a"

[[document]]
strategy = "brief"
name = "plumb"
source = [
  { path = "crates/cli/src", seal = "8a7d9cd0165e8ecb5c348055b98f4c3732a8d77232be9420e6c6592d47da8225" },
  { path = "crates/lib/src", seal = "34d34bb85cd75e2d906b5398cb466579b6d37117fe691274d4c05b02db732a39" },
  { path = "crates/macro/src", seal = "c8ae2bfd1091d77db6e6f010560bbf961644c87557ac3005e0bcb85723dd8f19" },
]
target-seal = "bd11f1189e9dc44ee85bbfaa9e44147f6868991adffea057f520fa2178e6ed9f"

[release]
product = "plumb"
authority = "https://releases.plumb.perish.uk"
binaries = ["plumb"]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
]
skill = true

[release.oci]
registry = "git.perish.top"
image = "perishlab/plumb"
account = "PerishFire"

[release.chart]
registry = "git.perish.top"
chart = "perishlab/plumb"
account = "PerishFire"

[release.cargo]
registry = "perish"
packages = ["plumb-macro", "plumb"]

[release.npm]
registry = "https://git.perish.top/api/packages/PerishLab/npm/"
packages = ["@perish/plumb"]

[release.cfworker]
account = "a6776d8a453d1b84d01576245a9c4f8d"
domain = "plumb.perish.uk"

[workflow.hash.guard]
"rust" = ["suite://cargo"]
"test" = ["*"]
"web" = ["suite://pnpm"]
"ectropy" = ["ectropy.toml", "apps", "crates", "docs", "packages", "skills"]
"plumb" = ["*"]
