[[document]]
strategy = "agent"
source = [{ path = ".", seal = "aeb3f403be7e2b614361f8d4a8e0e4b63c799d4d8babc010147f9cda35ff3ff0" }]
target-seal = "27b06e20e9fd6159d91103f2d3c94be33fff5f2a881363e3705d4cca36312bf0"

[[document]]
strategy = "brief"
name = "plumb"
source = [
  { path = "crates/cli/src", seal = "43e042b8991c23e957a1774183740f3aaf80c3c9f78b484ae3588490b3c3e88c" },
  { path = "crates/lib/src", seal = "2abb6bb36edd41426e67b2292d388a784d430f59e367f181f71609640bfffd91" },
  { path = "crates/macro/src", seal = "c8ae2bfd1091d77db6e6f010560bbf961644c87557ac3005e0bcb85723dd8f19" },
]
target-seal = "ba2971b700bd2a4f24077fb784e5d15038cf8f1cb419b226e25423c283074c48"

[release]
product = "plumb"
authority = "https://releases.plumb.perish.uk"
binaries = ["plumb"]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
]
skill = true

[release.oci]
registry = "git.perish.top"
image = "perishlab/plumb"
account = "PerishFire"

[release.chart]
registry = "git.perish.top"
chart = "perishlab/plumb"
account = "PerishFire"

[release.cargo]
registry = "perish"
packages = ["plumb-macro", "plumb"]

[release.npm]
registry = "https://git.perish.top/api/packages/PerishLab/npm/"
packages = ["@perish/plumb"]

[release.cfworker]
account = "a6776d8a453d1b84d01576245a9c4f8d"
domain = "plumb.perish.uk"
