name: guard

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  guard:
    runs-on: docker
    container: mirror.perish.lan/ci/deno
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install negentropy
        run: |
          set -eu
          curl -fsSL https://releases.negentropy.perish.uk/manage.sh | sh -s -- install --channel stable --version $(cat .runseal/negentropy.version) --bin-dir $HOME/.local/bin
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Guard
        run: |
          set -eu
          negentropy --strict .
